### ISSUE TITLE
Update to use Autocomplete Commands

### ISSUE THREAD

**Issue by JustCat80** [Geo1088/eris-docs-bot#13]
Please remind me November 24 or so if someone else hasn't done it by then, if it's not too hard I'll also add a "version" options to get the docs for a specific version

Possibly a vdocs command to pick a version as to not clutter the main one

Messages will be ephemeral probably with a button to send publicly

Might actually make a new repository actually if it's too messy here

**Comment by eritbh** [comment]
My command framework doesn't yet support slash commands (https://github.com/eritbh/yuuko/issues/93), so if this is an important issue for the server, either I'll need to spend more time working on adding support to my framework (probably more reasonable now that Eris 0.16 is out), or the code will have to be redone with a different framework (or without one).

**Comment by JustCat80** [comment]
Yea, I mean if I end up doing it I'm down to redo everything tbh, not too much I've already got everything I need in a template I created

**Comment by eritbh** [comment]
dono's fork exists pog
